name: tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  phpunit:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['8.2', '8.1']
        laravel: [9.*, 10.*]
        include:
          - laravel: 9.*
            testbench: 7.*
          - laravel: 10.*
            testbench: 8.*

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: curl, pdo, sqlite, pdo_sqlite

    - name: Install SQLite 3
      run: sudo apt-get install sqlite3

    - name: Install dependencies
      run: |
       composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
       composer update --prefer-stable --prefer-dist --no-interaction --no-suggest

    - name: Run test phpunit
      run: vendor/bin/phpunit
